### ISSUE TITLE
npm: package.json missing

### ISSUE THREAD

**Issue by adamellsworth** [PabloLec/neoss#6] opened 2021-09-23 06:05 UTC
from running `npm install -g neoss`

cli output
```
npm ERR! Could not install from ".nvm/versions/node/v12.22.6/lib/node_modules/neoss/src" as it does not contain a package.json file.
```

npm log
```
fetchPackageMetaData error for src@file:src Could not install from ".nvm/versions/node/v12.22.6/lib/node_modules/neoss/src" as it does not contain a package.json file.
```

**Comment by PabloLec** [comment] 2021-09-23 08:07
Hi,

That's peculiar, as I was able to install on various distros not related to dev environment without any error.
Anyway, that was probably caused by a line in `package.json` which was an artifact from previous imports configuration.

I removed that line, so this problem should be fixed.
Please try to install new version `npm install -g neoss@1.1.3`. Let me know if it fixed it. :wink:

**Comment by adamellsworth** [comment] 2021-09-23 21:39
resolved. Ty

**Closed** 2021-09-24 07:10 UTC
